[build-system]
requires = ["setuptools", "cython"]
build-backend = "setuptools.build_meta"

[project]
name = "pyop3"
version = "0.1"

[project.optional-dependencies]
tests = [
  "pytest",
  "pytest-mpi @ git+https://github.com/connorjward/pytest-mpi",
]

# TODO: Get this implemented along with black
# [tool.isort]
# profile = "black"
